"""Generate the full 62-table Oracle Fusion ERP schema for PostgreSQL 15."""
import os

HEADER = """-- ================================================================
-- Oracle Fusion AI Agent -- Enterprise Schema (62 tables)
-- PostgreSQL 15 | HCM(22) + Finance(23) + Procurement(17)
-- Generated by generate_schema.py
-- ================================================================

"""

def col(name, typ, *extras):
    parts = [f"    {name:<28s} {typ}"] + list(extras)
    return ",".join([parts[0]] + [f" {e}" for e in parts[1:]]) if len(parts)==1 else f"    {name:<28s} {typ} {' '.join(extras)}"

def tbl(name, columns, comment, constraints=None, indexes=None):
    lines = [f"\n-- {comment}", f"CREATE TABLE IF NOT EXISTS {name} ("]
    lines.append(",\n".join(columns))
    if constraints:
        lines[-1] += ","
        lines.append(",\n".join(constraints))
    lines.append(");")
    out = "\n".join(lines) + "\n"
    if indexes:
        for idx in indexes:
            out += f"{idx}\n"
    return out + "\n"

def pk(name):
    return f"    {name:<28s} SERIAL PRIMARY KEY"

def ts():
    return "    created_at                TIMESTAMP DEFAULT NOW()"

def ts2():
    return ["    created_at                TIMESTAMP DEFAULT NOW()",
            "    updated_at                TIMESTAMP DEFAULT NOW()"]

def fk(col_name, ref):
    return f"    {col_name:<28s} INTEGER REFERENCES {ref}"

def fk_r(col_name, ref):
    return f"    {col_name:<28s} INTEGER REFERENCES {ref} ON DELETE RESTRICT"

def idx(tname, *cols):
    iname = f"idx_{tname}_{'_'.join(cols)}"
    return f"CREATE INDEX IF NOT EXISTS {iname} ON {tname}({', '.join(cols)});"

def vc(name, size, *extras):
    e = " ".join(extras) if extras else ""
    return f"    {name:<28s} VARCHAR({size}){' ' + e if e else ''}"

def num(name, p=15, s=2, *extras):
    e = " ".join(extras) if extras else ""
    return f"    {name:<28s} NUMERIC({p},{s}){' ' + e if e else ''}"

def dt(name, *extras):
    e = " ".join(extras) if extras else ""
    return f"    {name:<28s} DATE{' ' + e if e else ''}"

def bool_col(name, default="TRUE"):
    return f"    {name:<28s} BOOLEAN DEFAULT {default}"

def int_col(name, *extras):
    e = " ".join(extras) if extras else ""
    return f"    {name:<28s} INTEGER{' ' + e if e else ''}"

def text_col(name):
    return f"    {name:<28s} TEXT"

def generate():
    sql = HEADER
    sql += "-- ================================================================\n"
    sql += "--                    SYSTEM TABLE\n"
    sql += "-- ================================================================\n"
    sql += tbl("ai_query_log", [
        pk("log_id"), text_col("user_query"), vc("detected_domain",30),
        text_col("generated_sql"), text_col("response_summary"),
        int_col("execution_time_ms"), ts()
    ], "AI agent query audit log")

    # ================================================================
    # HCM DOMAIN (22 tables)
    # ================================================================
    sql += "\n-- ================================================================\n"
    sql += "--                    HCM DOMAIN (22 TABLES)\n"
    sql += "-- ================================================================\n"

    # H1 hcm_persons
    sql += tbl("hcm_persons", [
        pk("person_id"), vc("person_number",20,"UNIQUE NOT NULL"),
        vc("first_name",80,"NOT NULL"), vc("last_name",80,"NOT NULL"),
        dt("date_of_birth"), vc("gender",10), vc("nationality",50),
        vc("national_id",30), vc("marital_status",20),
        vc("person_type",20,"DEFAULT 'EMPLOYEE'"),
        vc("status",20,"DEFAULT 'ACTIVE'"), *ts2()
    ], "H1: Core person identity -- no org/job context here",
    indexes=[idx("hcm_persons","status"), idx("hcm_persons","person_number")])

    # H2 hcm_person_names
    sql += tbl("hcm_person_names", [
        pk("person_name_id"), fk("person_id","hcm_persons(person_id) ON DELETE RESTRICT"),
        vc("name_type",20,"DEFAULT 'GLOBAL'"), vc("title",10),
        vc("first_name",80,"NOT NULL"), vc("middle_name",80),
        vc("last_name",80,"NOT NULL"), vc("suffix",10),
        dt("effective_from","NOT NULL"), dt("effective_to"), ts()
    ], "H2: Historical person names (legal name changes)",
    indexes=[idx("hcm_person_names","person_id")])

    # H3 hcm_person_emails
    sql += tbl("hcm_person_emails", [
        pk("email_id"), fk("person_id","hcm_persons(person_id) ON DELETE RESTRICT"),
        vc("email_type",20,"DEFAULT 'WORK'"), vc("email_address",150,"NOT NULL"),
        bool_col("is_primary"), ts()
    ], "H3: Person email addresses",
    indexes=[idx("hcm_person_emails","person_id")])

    # H4 hcm_organizations
    sql += tbl("hcm_organizations", [
        pk("org_id"), vc("org_code",20,"UNIQUE NOT NULL"),
        vc("org_name",150,"NOT NULL"),
        vc("org_type",30,"DEFAULT 'BUSINESS_UNIT'"),
        int_col("parent_org_id","REFERENCES hcm_organizations(org_id)"),
        vc("country",50,"DEFAULT 'United Kingdom'"),
        vc("status",20,"DEFAULT 'ACTIVE'"),
        dt("effective_from","DEFAULT CURRENT_DATE"), ts()
    ], "H4: Business units and legal entities (self-ref hierarchy)",
    indexes=[idx("hcm_organizations","parent_org_id")])

    # H5 hcm_locations
    sql += tbl("hcm_locations", [
        pk("location_id"), vc("location_code",20,"UNIQUE NOT NULL"),
        vc("location_name",100,"NOT NULL"), vc("address_line1",200),
        vc("city",50), vc("region",30), vc("postal_code",15),
        vc("country",50,"DEFAULT 'United Kingdom'"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "H5: Office and work locations")

    # H6 hcm_departments
    sql += tbl("hcm_departments", [
        pk("dept_id"), vc("dept_code",20,"UNIQUE NOT NULL"),
        vc("dept_name",100,"NOT NULL"),
        fk("org_id","hcm_organizations(org_id)"),
        vc("cost_centre_code",20),
        int_col("manager_person_id"),  # FK deferred
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "H6: Department master (FK→org; manager FK deferred to avoid circularity)",
    indexes=[idx("hcm_departments","org_id")])

    # H7 hcm_jobs
    sql += tbl("hcm_jobs", [
        pk("job_id"), vc("job_code",20,"UNIQUE NOT NULL"),
        vc("job_name",100,"NOT NULL"), vc("job_family",50),
        vc("job_level",20), num("min_salary",12,2), num("max_salary",12,2),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "H7: Job catalog / families")

    # H8 hcm_grades
    sql += tbl("hcm_grades", [
        pk("grade_id"), vc("grade_code",10,"UNIQUE NOT NULL"),
        vc("grade_name",50,"NOT NULL"),
        num("min_salary",12,2), num("mid_salary",12,2), num("max_salary",12,2),
        vc("currency",3,"DEFAULT 'GBP'"), ts()
    ], "H8: Grade ranges and salary bands")

    # H9 hcm_positions
    sql += tbl("hcm_positions", [
        pk("position_id"), vc("position_code",20,"UNIQUE NOT NULL"),
        vc("position_name",100,"NOT NULL"),
        fk("dept_id","hcm_departments(dept_id)"),
        fk("job_id","hcm_jobs(job_id)"),
        fk("location_id","hcm_locations(location_id)"),
        fk("grade_id","hcm_grades(grade_id)"),
        int_col("headcount_target","DEFAULT 1"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "H9: Position definitions (slot in org chart)",
    indexes=[idx("hcm_positions","dept_id"), idx("hcm_positions","job_id"),
             idx("hcm_positions","location_id"), idx("hcm_positions","grade_id")])

    # H10 hcm_assignments
    sql += tbl("hcm_assignments", [
        pk("assignment_id"), vc("assignment_number",20,"UNIQUE NOT NULL"),
        fk_r("person_id","hcm_persons(person_id)"),
        fk("position_id","hcm_positions(position_id)"),
        fk("dept_id","hcm_departments(dept_id)"),
        fk("org_id","hcm_organizations(org_id)"),
        fk("grade_id","hcm_grades(grade_id)"),
        fk("job_id","hcm_jobs(job_id)"),
        fk("location_id","hcm_locations(location_id)"),
        vc("assignment_type",20,"DEFAULT 'PRIMARY'"),
        vc("assignment_status",20,"DEFAULT 'ACTIVE'"),
        vc("employment_status",20,"DEFAULT 'ACTIVE'"),
        vc("job_title",100), num("salary",12,2),
        vc("salary_currency",3,"DEFAULT 'GBP'"),
        int_col("manager_person_id","REFERENCES hcm_persons(person_id)"),
        dt("effective_from","NOT NULL"), dt("effective_to"), *ts2()
    ], "H10: Assignment-based modeling -- ALL org context lives here",
    indexes=[idx("hcm_assignments","person_id"), idx("hcm_assignments","position_id"),
             idx("hcm_assignments","dept_id"), idx("hcm_assignments","org_id"),
             idx("hcm_assignments","manager_person_id")])

    # H11 hcm_employment_periods
    sql += tbl("hcm_employment_periods", [
        pk("employment_period_id"),
        fk_r("person_id","hcm_persons(person_id)"),
        vc("period_type",20,"DEFAULT 'EMPLOYEE'"),
        dt("start_date","NOT NULL"), dt("end_date"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "H11: Employment period spans (hire-to-terminate window)",
    indexes=[idx("hcm_employment_periods","person_id")])

    # H12 hcm_termination_reasons
    sql += tbl("hcm_termination_reasons", [
        pk("reason_id"), vc("reason_code",20,"UNIQUE NOT NULL"),
        vc("reason_name",100,"NOT NULL"), vc("reason_category",30),
        bool_col("is_voluntary"), ts()
    ], "H12: Termination reason lookup")

    # H13 hcm_workforce_actions
    sql += tbl("hcm_workforce_actions", [
        pk("action_id"),
        fk_r("person_id","hcm_persons(person_id)"),
        fk("assignment_id","hcm_assignments(assignment_id)"),
        vc("action_type",30,"NOT NULL"),
        vc("action_reason",100),
        dt("effective_date","NOT NULL"),
        int_col("reason_id","REFERENCES hcm_termination_reasons(reason_id)"),
        vc("old_value",200), vc("new_value",200),
        int_col("processed_by","REFERENCES hcm_persons(person_id)"),
        vc("status",20,"DEFAULT 'COMPLETED'"), ts()
    ], "H13: Workforce lifecycle actions (hire/transfer/promote/terminate)",
    indexes=[idx("hcm_workforce_actions","person_id"),
             idx("hcm_workforce_actions","assignment_id")])

    # H14 hcm_promotions
    sql += tbl("hcm_promotions", [
        pk("promotion_id"),
        fk_r("assignment_id","hcm_assignments(assignment_id)"),
        dt("effective_date","NOT NULL"),
        vc("old_grade",10), vc("new_grade",10),
        vc("old_job_title",100), vc("new_job_title",100),
        num("old_salary",12,2), num("new_salary",12,2),
        int_col("approved_by","REFERENCES hcm_persons(person_id)"),
        vc("status",20,"DEFAULT 'APPROVED'"), ts()
    ], "H14: Promotion history linked to assignment",
    indexes=[idx("hcm_promotions","assignment_id")])

    # H15 hcm_transfers
    sql += tbl("hcm_transfers", [
        pk("transfer_id"),
        fk_r("assignment_id","hcm_assignments(assignment_id)"),
        dt("effective_date","NOT NULL"),
        fk("from_dept_id","hcm_departments(dept_id)"),
        fk("to_dept_id","hcm_departments(dept_id)"),
        fk("from_location_id","hcm_locations(location_id)"),
        fk("to_location_id","hcm_locations(location_id)"),
        vc("transfer_reason",100),
        int_col("approved_by","REFERENCES hcm_persons(person_id)"),
        vc("status",20,"DEFAULT 'APPROVED'"), ts()
    ], "H15: Transfer history linked to assignment",
    indexes=[idx("hcm_transfers","assignment_id")])

    # H16 hcm_salary_history
    sql += tbl("hcm_salary_history", [
        pk("salary_history_id"),
        fk_r("assignment_id","hcm_assignments(assignment_id)"),
        num("old_salary",12,2), num("new_salary",12,2,"NOT NULL"),
        vc("change_reason",50), dt("effective_date","NOT NULL"),
        vc("currency",3,"DEFAULT 'GBP'"),
        int_col("approved_by","REFERENCES hcm_persons(person_id)"), ts()
    ], "H16: Salary change history per assignment",
    indexes=[idx("hcm_salary_history","assignment_id")])

    # H17 hcm_compensation_elements
    sql += tbl("hcm_compensation_elements", [
        pk("element_id"),
        fk_r("assignment_id","hcm_assignments(assignment_id)"),
        vc("element_type",30,"NOT NULL"), vc("element_name",100,"NOT NULL"),
        num("amount",12,2,"NOT NULL"),
        vc("frequency",20,"DEFAULT 'MONTHLY'"),
        vc("currency",3,"DEFAULT 'GBP'"),
        dt("effective_from"), dt("effective_to"), ts()
    ], "H17: Pay components (base, bonus, allowances) per assignment",
    indexes=[idx("hcm_compensation_elements","assignment_id")])

    # H18 hcm_payroll_runs
    sql += tbl("hcm_payroll_runs", [
        pk("payroll_run_id"), vc("run_name",100,"NOT NULL"),
        vc("period_name",20,"NOT NULL"), dt("run_date","NOT NULL"),
        vc("status",20,"DEFAULT 'COMPLETED'"),
        num("total_gross"), num("total_deductions"), num("total_net"),
        int_col("employee_count"), ts()
    ], "H18: Payroll batch run headers")

    # H19 hcm_payroll_results
    sql += tbl("hcm_payroll_results", [
        pk("result_id"),
        fk_r("payroll_run_id","hcm_payroll_runs(payroll_run_id)"),
        fk_r("assignment_id","hcm_assignments(assignment_id)"),
        num("gross_pay",12,2), num("tax_deducted",12,2),
        num("ni_deducted",12,2), num("pension_deducted",12,2),
        num("other_deductions",12,2,"DEFAULT 0"), num("net_pay",12,2),
        int_col("account_code_id"),  # FK added after fin_account_codes
        ts()
    ], "H19: Individual payroll results per assignment per run",
    indexes=[idx("hcm_payroll_results","payroll_run_id"),
             idx("hcm_payroll_results","assignment_id")])

    # H20 hcm_cost_allocations (cross-domain → fin_cost_centres deferred)
    sql += tbl("hcm_cost_allocations", [
        pk("allocation_id"),
        fk_r("assignment_id","hcm_assignments(assignment_id)"),
        int_col("cost_centre_id"),  # FK added after fin_cost_centres
        num("allocation_pct",5,2,"DEFAULT 100.00"),
        dt("effective_from","NOT NULL"), dt("effective_to"), ts()
    ], "H20: Assignment cost allocation to finance cost centres (cross-domain)",
    indexes=[idx("hcm_cost_allocations","assignment_id")])

    # H21 hcm_performance_reviews
    sql += tbl("hcm_performance_reviews", [
        pk("review_id"),
        fk_r("person_id","hcm_persons(person_id)"),
        int_col("reviewer_person_id","REFERENCES hcm_persons(person_id)"),
        vc("review_period",20,"NOT NULL"),
        vc("review_type",20,"DEFAULT 'ANNUAL'"),
        vc("overall_rating",30), num("rating_score",3,1),
        num("goals_met_pct",5,2), text_col("comments"),
        vc("status",20,"DEFAULT 'COMPLETED'"), dt("review_date"), ts()
    ], "H21: Performance reviews linked to person",
    indexes=[idx("hcm_performance_reviews","person_id")])

    # H22 hcm_training_records
    sql += tbl("hcm_training_records", [
        pk("training_id"),
        fk_r("person_id","hcm_persons(person_id)"),
        vc("course_name",150,"NOT NULL"), vc("course_category",50),
        vc("provider",100), dt("completion_date"),
        num("score",5,2), vc("status",20,"DEFAULT 'COMPLETED'"),
        vc("certificate_id",50), ts()
    ], "H22: Training and certification records",
    indexes=[idx("hcm_training_records","person_id")])

    # ================================================================
    # FINANCE DOMAIN (23 TABLES)
    # ================================================================
    sql += "\n-- ================================================================\n"
    sql += "--                    FINANCE DOMAIN (23 TABLES)\n"
    sql += "-- ================================================================\n"

    # F1 fin_ledgers
    sql += tbl("fin_ledgers", [
        pk("ledger_id"), vc("ledger_code",20,"UNIQUE NOT NULL"),
        vc("ledger_name",100,"NOT NULL"),
        vc("currency",3,"DEFAULT 'GBP'"),
        vc("calendar_type",20,"DEFAULT 'FISCAL'"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "F1: General ledger definitions")

    # F2 fin_chart_of_accounts
    sql += tbl("fin_chart_of_accounts", [
        pk("coa_id"), vc("coa_code",20,"UNIQUE NOT NULL"),
        vc("coa_name",100,"NOT NULL"),
        fk("ledger_id","fin_ledgers(ledger_id)"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "F2: Chart of accounts structure",
    indexes=[idx("fin_chart_of_accounts","ledger_id")])

    # F3 fin_coa_segments
    sql += tbl("fin_coa_segments", [
        pk("segment_id"),
        fk_r("coa_id","fin_chart_of_accounts(coa_id)"),
        vc("segment_name",50,"NOT NULL"),
        int_col("segment_number","NOT NULL"),
        vc("segment_type",30), vc("value_set",50), ts()
    ], "F3: COA segment definitions (company, dept, account, etc.)",
    indexes=[idx("fin_coa_segments","coa_id")])

    # F4 fin_cost_centres
    sql += tbl("fin_cost_centres", [
        pk("cost_centre_id"), vc("cost_centre_code",20,"UNIQUE NOT NULL"),
        vc("cost_centre_name",100,"NOT NULL"),
        fk("dept_id","hcm_departments(dept_id)"),
        int_col("manager_person_id","REFERENCES hcm_persons(person_id)"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "F4: Cost centre master (cross-domain link to HCM)",
    indexes=[idx("fin_cost_centres","dept_id")])

    # Now add deferred FKs
    sql += "\n-- Deferred FK: hcm_cost_allocations → fin_cost_centres\n"
    sql += "DO $$ BEGIN\n"
    sql += "  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_hcm_ca_cc') THEN\n"
    sql += "    ALTER TABLE hcm_cost_allocations ADD CONSTRAINT fk_hcm_ca_cc\n"
    sql += "      FOREIGN KEY (cost_centre_id) REFERENCES fin_cost_centres(cost_centre_id) ON DELETE RESTRICT;\n"
    sql += "  END IF;\n"
    sql += "END $$;\n"
    sql += "CREATE INDEX IF NOT EXISTS idx_hcm_cost_allocations_cost_centre_id ON hcm_cost_allocations(cost_centre_id);\n\n"

    # F5 fin_account_codes
    sql += tbl("fin_account_codes", [
        pk("account_code_id"), vc("account_code",20,"UNIQUE NOT NULL"),
        vc("account_name",100,"NOT NULL"),
        vc("account_type",30,"NOT NULL"),
        vc("parent_account_code",20),
        fk("coa_id","fin_chart_of_accounts(coa_id)"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "F5: Account code master",
    indexes=[idx("fin_account_codes","coa_id")])

    # Deferred FK: hcm_payroll_results.account_code_id
    sql += "-- Deferred FK: hcm_payroll_results → fin_account_codes\n"
    sql += "DO $$ BEGIN\n"
    sql += "  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_hcm_pr_ac') THEN\n"
    sql += "    ALTER TABLE hcm_payroll_results ADD CONSTRAINT fk_hcm_pr_ac\n"
    sql += "      FOREIGN KEY (account_code_id) REFERENCES fin_account_codes(account_code_id) ON DELETE RESTRICT;\n"
    sql += "  END IF;\n"
    sql += "END $$;\n"
    sql += "CREATE INDEX IF NOT EXISTS idx_hcm_payroll_results_account_code_id ON hcm_payroll_results(account_code_id);\n\n"

    # F6 fin_reporting_periods
    sql += tbl("fin_reporting_periods", [
        pk("period_id"), vc("period_name",20,"UNIQUE NOT NULL"),
        int_col("fiscal_year","NOT NULL"), int_col("fiscal_quarter","NOT NULL"),
        int_col("period_number","NOT NULL"),
        dt("start_date","NOT NULL"), dt("end_date","NOT NULL"),
        vc("status",20,"DEFAULT 'OPEN'"), ts()
    ], "F6: Fiscal reporting periods")

    # F7 fin_currency_rates
    sql += tbl("fin_currency_rates", [
        pk("rate_id"), vc("from_currency",3,"NOT NULL"),
        vc("to_currency",3,"NOT NULL"),
        num("exchange_rate",12,6,"NOT NULL"),
        vc("rate_type",20,"DEFAULT 'SPOT'"),
        dt("effective_date","NOT NULL"), ts()
    ], "F7: Currency exchange rates")

    # F8 fin_gl_journal_headers
    sql += tbl("fin_gl_journal_headers", [
        pk("journal_header_id"), vc("journal_number",30,"UNIQUE NOT NULL"),
        vc("journal_name",150),
        fk("ledger_id","fin_ledgers(ledger_id)"),
        fk("period_id","fin_reporting_periods(period_id)"),
        dt("journal_date","NOT NULL"),
        vc("journal_source",30), vc("journal_category",30),
        num("total_debit"), num("total_credit"),
        vc("status",20,"DEFAULT 'POSTED'"),
        int_col("created_by","REFERENCES hcm_persons(person_id)"),
        int_col("approved_by","REFERENCES hcm_persons(person_id)"), ts()
    ], "F8: GL journal entry headers",
    indexes=[idx("fin_gl_journal_headers","ledger_id"),
             idx("fin_gl_journal_headers","period_id")])

    # F9 fin_gl_journal_lines
    sql += tbl("fin_gl_journal_lines", [
        pk("journal_line_id"),
        fk_r("journal_header_id","fin_gl_journal_headers(journal_header_id)"),
        int_col("line_number","NOT NULL"),
        fk_r("account_code_id","fin_account_codes(account_code_id)"),
        fk_r("cost_centre_id","fin_cost_centres(cost_centre_id)"),
        num("debit_amount",15,2,"DEFAULT 0"), num("credit_amount",15,2,"DEFAULT 0"),
        vc("description",255), ts()
    ], "F9: GL journal lines with account + cost centre",
    indexes=[idx("fin_gl_journal_lines","journal_header_id"),
             idx("fin_gl_journal_lines","account_code_id"),
             idx("fin_gl_journal_lines","cost_centre_id")])

    # F10 fin_gl_balances
    sql += tbl("fin_gl_balances", [
        pk("balance_id"),
        fk("cost_centre_id","fin_cost_centres(cost_centre_id)"),
        fk("account_code_id","fin_account_codes(account_code_id)"),
        vc("period_name",20,"NOT NULL"),
        int_col("fiscal_year"), int_col("fiscal_quarter"),
        num("period_debit"), num("period_credit"), num("period_net"),
        num("begin_balance"), num("end_balance"),
        vc("currency",3,"DEFAULT 'GBP'"), ts()
    ], "F10: GL summary balances (derived from journal lines, not directly updated)",
    indexes=[idx("fin_gl_balances","cost_centre_id"),
             idx("fin_gl_balances","account_code_id"),
             idx("fin_gl_balances","period_name")])

    # F11 fin_budget_versions
    sql += tbl("fin_budget_versions", [
        pk("budget_version_id"),
        vc("version_name",50,"NOT NULL"),
        vc("version_type",20,"DEFAULT 'ORIGINAL'"),
        int_col("fiscal_year","NOT NULL"),
        vc("status",20,"DEFAULT 'APPROVED'"), ts()
    ], "F11: Budget version control (original, revised, forecast)")

    # F12 fin_budget_headers
    sql += tbl("fin_budget_headers", [
        pk("budget_header_id"), vc("budget_name",100,"NOT NULL"),
        fk("ledger_id","fin_ledgers(ledger_id)"),
        fk("budget_version_id","fin_budget_versions(budget_version_id)"),
        int_col("fiscal_year","NOT NULL"),
        num("total_amount"), vc("status",20,"DEFAULT 'APPROVED'"), ts()
    ], "F12: Budget headers per ledger",
    indexes=[idx("fin_budget_headers","ledger_id"),
             idx("fin_budget_headers","budget_version_id")])

    # F13 fin_budget_lines
    sql += tbl("fin_budget_lines", [
        pk("budget_line_id"),
        fk_r("budget_header_id","fin_budget_headers(budget_header_id)"),
        fk_r("cost_centre_id","fin_cost_centres(cost_centre_id)"),
        fk_r("account_code_id","fin_account_codes(account_code_id)"),
        vc("period_name",20,"NOT NULL"),
        num("amount","15","2","NOT NULL"), ts()
    ], "F13: Budget line amounts at cost centre + account level",
    indexes=[idx("fin_budget_lines","budget_header_id"),
             idx("fin_budget_lines","cost_centre_id"),
             idx("fin_budget_lines","account_code_id")])

    # ---- UNIFIED SUPPLIER MASTER ----
    sql += "\n-- ================================================================\n"
    sql += "--               UNIFIED SUPPLIER MASTER (3 TABLES)\n"
    sql += "-- ================================================================\n"

    # S1 sup_suppliers
    sql += tbl("sup_suppliers", [
        pk("supplier_id"), vc("supplier_number",20,"UNIQUE NOT NULL"),
        vc("supplier_name",150,"NOT NULL"),
        vc("tax_registration",30), vc("payment_terms",30,"DEFAULT 'NET30'"),
        vc("supplier_type",30), vc("risk_rating",10),
        vc("qualification_status",20,"DEFAULT 'QUALIFIED'"),
        vc("status",20,"DEFAULT 'ACTIVE'"),
        vc("country",50,"DEFAULT 'United Kingdom'"), *ts2()
    ], "Unified supplier master -- referenced by BOTH Finance AP and Procurement",
    indexes=[idx("sup_suppliers","status")])

    # S2 sup_supplier_sites
    sql += tbl("sup_supplier_sites", [
        pk("site_id"),
        fk_r("supplier_id","sup_suppliers(supplier_id)"),
        vc("site_code",20,"NOT NULL"), vc("site_name",100),
        vc("address_line1",200), vc("city",50),
        vc("postal_code",15),
        vc("country",50,"DEFAULT 'United Kingdom'"),
        bool_col("is_primary","FALSE"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "Supplier sites / addresses",
    indexes=[idx("sup_supplier_sites","supplier_id")])

    # S3 sup_supplier_contacts
    sql += tbl("sup_supplier_contacts", [
        pk("contact_id"),
        fk_r("supplier_id","sup_suppliers(supplier_id)"),
        vc("contact_name",100,"NOT NULL"), vc("job_title",100),
        vc("email",150), vc("phone",30),
        bool_col("is_primary","FALSE"), ts()
    ], "Supplier contact persons",
    indexes=[idx("sup_supplier_contacts","supplier_id")])

    # ---- AP ----
    sql += "\n-- ---- Accounts Payable ----\n"

    # F14 fin_ap_invoices
    sql += tbl("fin_ap_invoices", [
        pk("invoice_id"), vc("invoice_number",50,"UNIQUE NOT NULL"),
        fk_r("supplier_id","sup_suppliers(supplier_id)"),
        fk("ledger_id","fin_ledgers(ledger_id)"),
        dt("invoice_date","NOT NULL"), dt("due_date"),
        num("invoice_amount","15","2","NOT NULL"),
        num("paid_amount",15,2,"DEFAULT 0"),
        num("outstanding_amount"),
        vc("currency",3,"DEFAULT 'GBP'"),
        vc("status",20,"DEFAULT 'PENDING'"),
        int_col("created_by","REFERENCES hcm_persons(person_id)"),
        int_col("approved_by","REFERENCES hcm_persons(person_id)"), *ts2()
    ], "F14: AP invoices referencing unified supplier master",
    indexes=[idx("fin_ap_invoices","supplier_id"),
             idx("fin_ap_invoices","status"),
             idx("fin_ap_invoices","due_date")])

    # F15 fin_ap_invoice_lines (po_line_id FK deferred)
    sql += tbl("fin_ap_invoice_lines", [
        pk("invoice_line_id"),
        fk_r("invoice_id","fin_ap_invoices(invoice_id)"),
        int_col("line_number","NOT NULL"),
        vc("description",255),
        num("quantity",10,2,"DEFAULT 1"), num("unit_price",12,2),
        num("line_amount",12,2),
        int_col("po_line_id"),  # FK deferred until proc_po_lines exists
        ts()
    ], "F15: AP invoice lines (po_line_id FK deferred for 3-way match)",
    indexes=[idx("fin_ap_invoice_lines","invoice_id")])

    # F16 fin_ap_invoice_distributions
    sql += tbl("fin_ap_invoice_distributions", [
        pk("distribution_id"),
        fk_r("invoice_line_id","fin_ap_invoice_lines(invoice_line_id)"),
        fk_r("cost_centre_id","fin_cost_centres(cost_centre_id)"),
        fk_r("account_code_id","fin_account_codes(account_code_id)"),
        num("distribution_pct",5,2,"DEFAULT 100.00"),
        num("amount",12,2), ts()
    ], "F16: AP invoice accounting distributions",
    indexes=[idx("fin_ap_invoice_distributions","invoice_line_id"),
             idx("fin_ap_invoice_distributions","cost_centre_id"),
             idx("fin_ap_invoice_distributions","account_code_id")])

    # F17 fin_ap_payment_schedules
    sql += tbl("fin_ap_payment_schedules", [
        pk("schedule_id"),
        fk_r("invoice_id","fin_ap_invoices(invoice_id)"),
        int_col("installment_num","DEFAULT 1"),
        dt("due_date","NOT NULL"),
        num("amount_due",12,2,"NOT NULL"),
        num("amount_paid",12,2,"DEFAULT 0"),
        vc("status",20,"DEFAULT 'OPEN'"), ts()
    ], "F17: AP payment schedules per invoice",
    indexes=[idx("fin_ap_payment_schedules","invoice_id")])

    # F18 fin_ap_payments
    sql += tbl("fin_ap_payments", [
        pk("payment_id"), vc("payment_number",30,"UNIQUE NOT NULL"),
        fk_r("supplier_id","sup_suppliers(supplier_id)"),
        dt("payment_date","NOT NULL"),
        num("payment_amount","15","2","NOT NULL"),
        vc("payment_method",20,"DEFAULT 'BACS'"),
        vc("reference",50),
        vc("status",20,"DEFAULT 'COMPLETED'"), ts()
    ], "F18: AP payment records",
    indexes=[idx("fin_ap_payments","supplier_id")])

    # ---- AR ----
    sql += "\n-- ---- Accounts Receivable ----\n"

    # F19 fin_ar_customers
    sql += tbl("fin_ar_customers", [
        pk("customer_id"), vc("customer_number",20,"UNIQUE NOT NULL"),
        vc("customer_name",150,"NOT NULL"),
        vc("customer_type",30), vc("payment_terms",30,"DEFAULT 'NET30'"),
        num("credit_limit"), vc("contact_name",100),
        vc("contact_email",150),
        vc("country",50,"DEFAULT 'United Kingdom'"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "F19: AR customer master")

    # F20 fin_ar_invoices
    sql += tbl("fin_ar_invoices", [
        pk("ar_invoice_id"), vc("invoice_number",50,"UNIQUE NOT NULL"),
        fk_r("customer_id","fin_ar_customers(customer_id)"),
        dt("invoice_date","NOT NULL"), dt("due_date","NOT NULL"),
        num("invoice_amount","15","2","NOT NULL"),
        num("paid_amount",15,2,"DEFAULT 0"), num("outstanding"),
        vc("currency",3,"DEFAULT 'GBP'"),
        vc("status",20,"DEFAULT 'OPEN'"), ts()
    ], "F20: AR invoices",
    indexes=[idx("fin_ar_invoices","customer_id")])

    # F21 fin_ar_receipts
    sql += tbl("fin_ar_receipts", [
        pk("receipt_id"), vc("receipt_number",30,"UNIQUE NOT NULL"),
        fk_r("ar_invoice_id","fin_ar_invoices(ar_invoice_id)"),
        dt("receipt_date","NOT NULL"), num("receipt_amount","15","2","NOT NULL"),
        vc("payment_method",20,"DEFAULT 'BACS'"),
        vc("status",20,"DEFAULT 'APPLIED'"), ts()
    ], "F21: AR receipts (customer payments)",
    indexes=[idx("fin_ar_receipts","ar_invoice_id")])

    # ================================================================
    # PROCUREMENT DOMAIN (17 TABLES)
    # ================================================================
    sql += "\n-- ================================================================\n"
    sql += "--                 PROCUREMENT DOMAIN (17 TABLES)\n"
    sql += "-- ================================================================\n"

    # P1 proc_item_categories
    sql += tbl("proc_item_categories", [
        pk("category_id"), vc("category_code",20,"UNIQUE NOT NULL"),
        vc("category_name",100,"NOT NULL"),
        int_col("parent_category_id","REFERENCES proc_item_categories(category_id)"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "P1: Item category hierarchy (self-referencing)",
    indexes=[idx("proc_item_categories","parent_category_id")])

    # P2 proc_items
    sql += tbl("proc_items", [
        pk("item_id"), vc("item_code",20,"UNIQUE NOT NULL"),
        vc("item_name",150,"NOT NULL"), vc("description",255),
        fk("category_id","proc_item_categories(category_id)"),
        vc("unit_of_measure",20,"DEFAULT 'EACH'"),
        num("unit_price",12,2),
        vc("item_type",20,"DEFAULT 'SERVICE'"),
        vc("status",20,"DEFAULT 'ACTIVE'"), ts()
    ], "P2: Item / service catalog",
    indexes=[idx("proc_items","category_id")])

    # P3 proc_requisition_headers
    sql += tbl("proc_requisition_headers", [
        pk("requisition_id"), vc("requisition_number",30,"UNIQUE NOT NULL"),
        fk("requester_id","hcm_persons(person_id)"),
        fk("dept_id","hcm_departments(dept_id)"),
        vc("description",255), text_col("justification"),
        num("total_amount"), vc("status",20,"DEFAULT 'APPROVED'"),
        dt("submitted_date"), dt("approved_date"),
        int_col("approved_by","REFERENCES hcm_persons(person_id)"), *ts2()
    ], "P3: Purchase requisition headers (cross-domain → HCM)",
    indexes=[idx("proc_requisition_headers","requester_id"),
             idx("proc_requisition_headers","dept_id")])

    # P4 proc_requisition_lines
    sql += tbl("proc_requisition_lines", [
        pk("req_line_id"),
        fk_r("requisition_id","proc_requisition_headers(requisition_id)"),
        int_col("line_number","NOT NULL"),
        fk("item_id","proc_items(item_id)"),
        vc("description",255),
        num("quantity",10,2,"DEFAULT 1"), num("unit_price",12,2),
        num("line_amount",12,2), dt("need_by_date"), ts()
    ], "P4: Requisition line items",
    indexes=[idx("proc_requisition_lines","requisition_id"),
             idx("proc_requisition_lines","item_id")])

    # P5 proc_requisition_distributions
    sql += tbl("proc_requisition_distributions", [
        pk("req_dist_id"),
        fk_r("req_line_id","proc_requisition_lines(req_line_id)"),
        fk_r("cost_centre_id","fin_cost_centres(cost_centre_id)"),
        fk_r("account_code_id","fin_account_codes(account_code_id)"),
        num("distribution_pct",5,2,"DEFAULT 100.00"),
        num("amount",12,2), ts()
    ], "P5: Requisition accounting distributions",
    indexes=[idx("proc_requisition_distributions","req_line_id"),
             idx("proc_requisition_distributions","cost_centre_id"),
             idx("proc_requisition_distributions","account_code_id")])

    # P6 proc_quotation_headers
    sql += tbl("proc_quotation_headers", [
        pk("quotation_header_id"), vc("quotation_number",30,"UNIQUE NOT NULL"),
        vc("engagement_id",30,"NOT NULL"), vc("engagement_name",200),
        fk_r("supplier_id","sup_suppliers(supplier_id)"),
        num("original_amount"), num("revised_amount"),
        vc("status",20), dt("submission_date"),
        vc("category",50), *ts2()
    ], "P6: Quotation headers linked to unified supplier",
    indexes=[idx("proc_quotation_headers","supplier_id"),
             idx("proc_quotation_headers","engagement_id")])

    # P7 proc_quotation_lines
    sql += tbl("proc_quotation_lines", [
        pk("quot_line_id"),
        fk_r("quotation_header_id","proc_quotation_headers(quotation_header_id)"),
        int_col("line_number","NOT NULL"),
        fk("item_id","proc_items(item_id)"),
        vc("description",255),
        num("quantity",10,2,"DEFAULT 1"), num("unit_price",12,2),
        num("line_amount",12,2), ts()
    ], "P7: Quotation line items",
    indexes=[idx("proc_quotation_lines","quotation_header_id")])

    # P8 proc_quote_versions
    sql += tbl("proc_quote_versions", [
        pk("version_id"),
        fk_r("quotation_header_id","proc_quotation_headers(quotation_header_id)"),
        int_col("version_number","NOT NULL"),
        num("version_amount"), dt("submitted_date"),
        vc("status",20), text_col("change_notes"), ts()
    ], "P8: Quotation version history for audit trail",
    indexes=[idx("proc_quote_versions","quotation_header_id")])

    # P9 proc_po_headers
    sql += tbl("proc_po_headers", [
        pk("po_header_id"), vc("po_number",50,"UNIQUE NOT NULL"),
        fk_r("supplier_id","sup_suppliers(supplier_id)"),
        fk("requisition_id","proc_requisition_headers(requisition_id)"),
        fk("buyer_id","hcm_persons(person_id)"),
        num("total_amount"), num("approved_amount"),
        vc("status",20,"DEFAULT 'PENDING'"),
        dt("created_date"), dt("approved_date"),
        int_col("approved_by","REFERENCES hcm_persons(person_id)"),
        vc("category",50), *ts2()
    ], "P9: PO headers (cross-domain → supplier + HCM buyer)",
    indexes=[idx("proc_po_headers","supplier_id"),
             idx("proc_po_headers","buyer_id"),
             idx("proc_po_headers","requisition_id"),
             idx("proc_po_headers","status")])

    # P10 proc_po_lines
    sql += tbl("proc_po_lines", [
        pk("po_line_id"),
        fk_r("po_header_id","proc_po_headers(po_header_id)"),
        int_col("line_number","NOT NULL"),
        fk("item_id","proc_items(item_id)"),
        vc("description",255),
        num("quantity",10,2,"DEFAULT 1"), num("unit_price",12,2),
        num("line_amount",12,2),
        vc("status",20,"DEFAULT 'OPEN'"), ts()
    ], "P10: PO line items",
    indexes=[idx("proc_po_lines","po_header_id"),
             idx("proc_po_lines","item_id")])

    # Deferred FK: fin_ap_invoice_lines.po_line_id → proc_po_lines
    sql += "-- Deferred FK: fin_ap_invoice_lines.po_line_id → proc_po_lines (3-way match)\n"
    sql += "DO $$ BEGIN\n"
    sql += "  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_ap_il_pol') THEN\n"
    sql += "    ALTER TABLE fin_ap_invoice_lines ADD CONSTRAINT fk_ap_il_pol\n"
    sql += "      FOREIGN KEY (po_line_id) REFERENCES proc_po_lines(po_line_id) ON DELETE RESTRICT;\n"
    sql += "  END IF;\n"
    sql += "END $$;\n"
    sql += "CREATE INDEX IF NOT EXISTS idx_fin_ap_invoice_lines_po_line_id ON fin_ap_invoice_lines(po_line_id);\n\n"

    # P11 proc_po_distributions
    sql += tbl("proc_po_distributions", [
        pk("po_dist_id"),
        fk_r("po_line_id","proc_po_lines(po_line_id)"),
        fk_r("cost_centre_id","fin_cost_centres(cost_centre_id)"),
        fk_r("account_code_id","fin_account_codes(account_code_id)"),
        num("distribution_pct",5,2,"DEFAULT 100.00"),
        num("amount",12,2), ts()
    ], "P11: PO accounting distributions (cross-domain → Finance)",
    indexes=[idx("proc_po_distributions","po_line_id"),
             idx("proc_po_distributions","cost_centre_id"),
             idx("proc_po_distributions","account_code_id")])

    # P12 proc_po_approvals
    sql += tbl("proc_po_approvals", [
        pk("approval_id"),
        fk_r("po_header_id","proc_po_headers(po_header_id)"),
        int_col("approver_id","REFERENCES hcm_persons(person_id)"),
        int_col("approval_level","DEFAULT 1"),
        vc("action",20,"NOT NULL"),
        text_col("comments"),
        dt("action_date","NOT NULL"),
        vc("status",20,"DEFAULT 'APPROVED'"), ts()
    ], "P12: PO approval workflow",
    indexes=[idx("proc_po_approvals","po_header_id")])

    # P13 proc_receipt_headers
    sql += tbl("proc_receipt_headers", [
        pk("receipt_header_id"), vc("receipt_number",30,"UNIQUE NOT NULL"),
        fk_r("po_header_id","proc_po_headers(po_header_id)"),
        int_col("received_by","REFERENCES hcm_persons(person_id)"),
        dt("receipt_date","NOT NULL"),
        vc("status",20,"DEFAULT 'RECEIVED'"),
        text_col("comments"), ts()
    ], "P13: Goods receipt headers",
    indexes=[idx("proc_receipt_headers","po_header_id")])

    # P14 proc_receipt_lines
    sql += tbl("proc_receipt_lines", [
        pk("receipt_line_id"),
        fk_r("receipt_header_id","proc_receipt_headers(receipt_header_id)"),
        fk_r("po_line_id","proc_po_lines(po_line_id)"),
        num("quantity_received",10,2),
        num("quantity_accepted",10,2),
        num("quantity_rejected",10,2,"DEFAULT 0"),
        vc("inspection_status",20,"DEFAULT 'ACCEPTED'"), ts()
    ], "P14: Goods receipt lines matched to PO lines",
    indexes=[idx("proc_receipt_lines","receipt_header_id"),
             idx("proc_receipt_lines","po_line_id")])

    # P15 proc_contract_headers
    sql += tbl("proc_contract_headers", [
        pk("contract_header_id"), vc("contract_number",30,"UNIQUE NOT NULL"),
        vc("contract_name",200),
        fk_r("supplier_id","sup_suppliers(supplier_id)"),
        vc("contract_type",30,"DEFAULT 'BLANKET'"),
        dt("start_date"), dt("end_date"),
        num("total_value"), num("released_amount",15,2,"DEFAULT 0"),
        vc("status",20,"DEFAULT 'ACTIVE'"),
        int_col("owner_id","REFERENCES hcm_persons(person_id)"), ts()
    ], "P15: Supplier / blanket purchase contracts",
    indexes=[idx("proc_contract_headers","supplier_id")])

    # P16 proc_contract_lines
    sql += tbl("proc_contract_lines", [
        pk("contract_line_id"),
        fk_r("contract_header_id","proc_contract_headers(contract_header_id)"),
        int_col("line_number","NOT NULL"),
        fk("item_id","proc_items(item_id)"),
        vc("description",255),
        num("quantity",10,2), num("unit_price",12,2),
        num("line_amount",12,2),
        num("released_amount",12,2,"DEFAULT 0"), ts()
    ], "P16: Contract line items",
    indexes=[idx("proc_contract_lines","contract_header_id")])

    # ================================================================
    # LEGACY COMPATIBILITY VIEWS
    # ================================================================
    sql += "\n-- ================================================================\n"
    sql += "--   LEGACY COMPATIBILITY: Views matching old 5-table schema\n"
    sql += "--   so existing tools/queries still work\n"
    sql += "-- ================================================================\n\n"

    sql += """-- View: hcm_employees (maps to hcm_persons + hcm_assignments)
CREATE OR REPLACE VIEW hcm_employees AS
SELECT
    p.person_id                AS employee_id,
    p.person_number            AS employee_number,
    pn.first_name || ' ' || pn.last_name AS full_name,
    pe.email_address           AS email,
    d.dept_name                AS department,
    a.job_title,
    g.grade_code               AS grade_level,
    a.salary,
    ep.start_date              AS hire_date,
    ep.end_date                AS termination_date,
    a.employment_status        AS employment_status,
    l.location_name            AS location,
    a.manager_person_id        AS manager_id,
    a.dept_id,
    a.position_id,
    a.grade_id,
    a.location_id,
    p.nationality,
    p.date_of_birth,
    p.gender,
    p.created_at
FROM hcm_persons p
LEFT JOIN hcm_person_names pn ON pn.person_id = p.person_id
    AND pn.effective_to IS NULL AND pn.name_type = 'GLOBAL'
LEFT JOIN hcm_person_emails pe ON pe.person_id = p.person_id AND pe.is_primary = TRUE
LEFT JOIN hcm_assignments a ON a.person_id = p.person_id
    AND a.assignment_type = 'PRIMARY' AND a.assignment_status = 'ACTIVE'
LEFT JOIN hcm_employment_periods ep ON ep.person_id = p.person_id
    AND ep.status = 'ACTIVE'
LEFT JOIN hcm_departments d ON d.dept_id = a.dept_id
LEFT JOIN hcm_grades g ON g.grade_id = a.grade_id
LEFT JOIN hcm_locations l ON l.location_id = a.location_id;

-- View: procurement_quotations (maps to proc_quotation_headers + proc_quote_versions)
CREATE OR REPLACE VIEW procurement_quotations AS
SELECT
    qh.quotation_header_id     AS quotation_id,
    qh.engagement_id,
    qh.engagement_name,
    s.supplier_name,
    qh.original_amount,
    qh.revised_amount,
    qv.version_number          AS quotation_version,
    COALESCE(qv.status, qh.status) AS status,
    COALESCE(qv.submitted_date, qh.submission_date) AS submission_date,
    qh.category,
    qh.supplier_id,
    qh.created_at
FROM proc_quotation_headers qh
LEFT JOIN sup_suppliers s ON s.supplier_id = qh.supplier_id
LEFT JOIN proc_quote_versions qv ON qv.quotation_header_id = qh.quotation_header_id;

-- View: procurement_purchase_orders (maps to proc_po_headers)
CREATE OR REPLACE VIEW procurement_purchase_orders AS
SELECT
    ph.po_header_id            AS po_id,
    ph.po_number,
    s.supplier_name,
    ph.total_amount,
    ph.approved_amount,
    ph.status,
    ph.created_date,
    ph.approved_date,
    cc.cost_centre_code        AS cost_centre,
    ph.category,
    ph.supplier_id,
    ph.buyer_id,
    ph.created_at
FROM proc_po_headers ph
LEFT JOIN sup_suppliers s ON s.supplier_id = ph.supplier_id
LEFT JOIN proc_po_distributions pd ON pd.po_line_id = (
    SELECT pl.po_line_id FROM proc_po_lines pl WHERE pl.po_header_id = ph.po_header_id LIMIT 1
)
LEFT JOIN fin_cost_centres cc ON cc.cost_centre_id = pd.cost_centre_id;

"""

    return sql


if __name__ == "__main__":
    sql = generate()
    outpath = os.path.join(os.path.dirname(__file__), "schema.sql")
    with open(outpath, "w", encoding="utf-8") as f:
        f.write(sql)
    # Count tables
    table_count = sql.count("CREATE TABLE IF NOT EXISTS")
    view_count = sql.count("CREATE OR REPLACE VIEW")
    fk_count = sql.count("REFERENCES")
    idx_count = sql.count("CREATE INDEX")
    print(f"Generated schema.sql:")
    print(f"  Tables: {table_count}")
    print(f"  Views:  {view_count}")
    print(f"  FKs:    {fk_count}")
    print(f"  Indexes:{idx_count}")
    print(f"  Size:   {len(sql):,} bytes")
