-- ================================================================
-- Oracle Fusion AI Agent -- Enterprise Schema (62 tables)
-- PostgreSQL 15 | HCM(22) + Finance(23) + Procurement(17)
-- Generated by generate_schema.py
-- ================================================================

-- ================================================================
--                    SYSTEM TABLE
-- ================================================================

-- AI agent query audit log
CREATE TABLE IF NOT EXISTS ai_query_log (
    log_id                       SERIAL PRIMARY KEY,
    user_query                   TEXT,
    detected_domain              VARCHAR(30),
    generated_sql                TEXT,
    response_summary             TEXT,
    execution_time_ms            INTEGER,
    created_at                TIMESTAMP DEFAULT NOW()
);


-- ================================================================
--                    HCM DOMAIN (22 TABLES)
-- ================================================================

-- H1: Core person identity -- no org/job context here
CREATE TABLE IF NOT EXISTS hcm_persons (
    person_id                    SERIAL PRIMARY KEY,
    person_number                VARCHAR(20) UNIQUE NOT NULL,
    first_name                   VARCHAR(80) NOT NULL,
    last_name                    VARCHAR(80) NOT NULL,
    date_of_birth                DATE,
    gender                       VARCHAR(10),
    nationality                  VARCHAR(50),
    national_id                  VARCHAR(30),
    marital_status               VARCHAR(20),
    person_type                  VARCHAR(20) DEFAULT 'EMPLOYEE',
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW(),
    updated_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_persons_status ON hcm_persons(status);
CREATE INDEX IF NOT EXISTS idx_hcm_persons_person_number ON hcm_persons(person_number);


-- H2: Historical person names (legal name changes)
CREATE TABLE IF NOT EXISTS hcm_person_names (
    person_name_id               SERIAL PRIMARY KEY,
    person_id                    INTEGER REFERENCES hcm_persons(person_id) ON DELETE RESTRICT,
    name_type                    VARCHAR(20) DEFAULT 'GLOBAL',
    title                        VARCHAR(10),
    first_name                   VARCHAR(80) NOT NULL,
    middle_name                  VARCHAR(80),
    last_name                    VARCHAR(80) NOT NULL,
    suffix                       VARCHAR(10),
    effective_from               DATE NOT NULL,
    effective_to                 DATE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_person_names_person_id ON hcm_person_names(person_id);


-- H3: Person email addresses
CREATE TABLE IF NOT EXISTS hcm_person_emails (
    email_id                     SERIAL PRIMARY KEY,
    person_id                    INTEGER REFERENCES hcm_persons(person_id) ON DELETE RESTRICT,
    email_type                   VARCHAR(20) DEFAULT 'WORK',
    email_address                VARCHAR(150) NOT NULL,
    is_primary                   BOOLEAN DEFAULT TRUE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_person_emails_person_id ON hcm_person_emails(person_id);


-- H4: Business units and legal entities (self-ref hierarchy)
CREATE TABLE IF NOT EXISTS hcm_organizations (
    org_id                       SERIAL PRIMARY KEY,
    org_code                     VARCHAR(20) UNIQUE NOT NULL,
    org_name                     VARCHAR(150) NOT NULL,
    org_type                     VARCHAR(30) DEFAULT 'BUSINESS_UNIT',
    parent_org_id                INTEGER REFERENCES hcm_organizations(org_id),
    country                      VARCHAR(50) DEFAULT 'United Kingdom',
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    effective_from               DATE DEFAULT CURRENT_DATE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_organizations_parent_org_id ON hcm_organizations(parent_org_id);


-- H5: Office and work locations
CREATE TABLE IF NOT EXISTS hcm_locations (
    location_id                  SERIAL PRIMARY KEY,
    location_code                VARCHAR(20) UNIQUE NOT NULL,
    location_name                VARCHAR(100) NOT NULL,
    address_line1                VARCHAR(200),
    city                         VARCHAR(50),
    region                       VARCHAR(30),
    postal_code                  VARCHAR(15),
    country                      VARCHAR(50) DEFAULT 'United Kingdom',
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);


-- H6: Department master (FK→org; manager FK deferred to avoid circularity)
CREATE TABLE IF NOT EXISTS hcm_departments (
    dept_id                      SERIAL PRIMARY KEY,
    dept_code                    VARCHAR(20) UNIQUE NOT NULL,
    dept_name                    VARCHAR(100) NOT NULL,
    org_id                       INTEGER REFERENCES hcm_organizations(org_id),
    cost_centre_code             VARCHAR(20),
    manager_person_id            INTEGER,
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_departments_org_id ON hcm_departments(org_id);


-- H7: Job catalog / families
CREATE TABLE IF NOT EXISTS hcm_jobs (
    job_id                       SERIAL PRIMARY KEY,
    job_code                     VARCHAR(20) UNIQUE NOT NULL,
    job_name                     VARCHAR(100) NOT NULL,
    job_family                   VARCHAR(50),
    job_level                    VARCHAR(20),
    min_salary                   NUMERIC(12,2),
    max_salary                   NUMERIC(12,2),
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);


-- H8: Grade ranges and salary bands
CREATE TABLE IF NOT EXISTS hcm_grades (
    grade_id                     SERIAL PRIMARY KEY,
    grade_code                   VARCHAR(10) UNIQUE NOT NULL,
    grade_name                   VARCHAR(50) NOT NULL,
    min_salary                   NUMERIC(12,2),
    mid_salary                   NUMERIC(12,2),
    max_salary                   NUMERIC(12,2),
    currency                     VARCHAR(3) DEFAULT 'GBP',
    created_at                TIMESTAMP DEFAULT NOW()
);


-- H9: Position definitions (slot in org chart)
CREATE TABLE IF NOT EXISTS hcm_positions (
    position_id                  SERIAL PRIMARY KEY,
    position_code                VARCHAR(20) UNIQUE NOT NULL,
    position_name                VARCHAR(100) NOT NULL,
    dept_id                      INTEGER REFERENCES hcm_departments(dept_id),
    job_id                       INTEGER REFERENCES hcm_jobs(job_id),
    location_id                  INTEGER REFERENCES hcm_locations(location_id),
    grade_id                     INTEGER REFERENCES hcm_grades(grade_id),
    headcount_target             INTEGER DEFAULT 1,
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_positions_dept_id ON hcm_positions(dept_id);
CREATE INDEX IF NOT EXISTS idx_hcm_positions_job_id ON hcm_positions(job_id);
CREATE INDEX IF NOT EXISTS idx_hcm_positions_location_id ON hcm_positions(location_id);
CREATE INDEX IF NOT EXISTS idx_hcm_positions_grade_id ON hcm_positions(grade_id);


-- H10: Assignment-based modeling -- ALL org context lives here
CREATE TABLE IF NOT EXISTS hcm_assignments (
    assignment_id                SERIAL PRIMARY KEY,
    assignment_number            VARCHAR(20) UNIQUE NOT NULL,
    person_id                    INTEGER REFERENCES hcm_persons(person_id) ON DELETE RESTRICT,
    position_id                  INTEGER REFERENCES hcm_positions(position_id),
    dept_id                      INTEGER REFERENCES hcm_departments(dept_id),
    org_id                       INTEGER REFERENCES hcm_organizations(org_id),
    grade_id                     INTEGER REFERENCES hcm_grades(grade_id),
    job_id                       INTEGER REFERENCES hcm_jobs(job_id),
    location_id                  INTEGER REFERENCES hcm_locations(location_id),
    assignment_type              VARCHAR(20) DEFAULT 'PRIMARY',
    assignment_status            VARCHAR(20) DEFAULT 'ACTIVE',
    employment_status            VARCHAR(20) DEFAULT 'ACTIVE',
    job_title                    VARCHAR(100),
    salary                       NUMERIC(12,2),
    salary_currency              VARCHAR(3) DEFAULT 'GBP',
    manager_person_id            INTEGER REFERENCES hcm_persons(person_id),
    effective_from               DATE NOT NULL,
    effective_to                 DATE,
    created_at                TIMESTAMP DEFAULT NOW(),
    updated_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_assignments_person_id ON hcm_assignments(person_id);
CREATE INDEX IF NOT EXISTS idx_hcm_assignments_position_id ON hcm_assignments(position_id);
CREATE INDEX IF NOT EXISTS idx_hcm_assignments_dept_id ON hcm_assignments(dept_id);
CREATE INDEX IF NOT EXISTS idx_hcm_assignments_org_id ON hcm_assignments(org_id);
CREATE INDEX IF NOT EXISTS idx_hcm_assignments_manager_person_id ON hcm_assignments(manager_person_id);


-- H11: Employment period spans (hire-to-terminate window)
CREATE TABLE IF NOT EXISTS hcm_employment_periods (
    employment_period_id         SERIAL PRIMARY KEY,
    person_id                    INTEGER REFERENCES hcm_persons(person_id) ON DELETE RESTRICT,
    period_type                  VARCHAR(20) DEFAULT 'EMPLOYEE',
    start_date                   DATE NOT NULL,
    end_date                     DATE,
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_employment_periods_person_id ON hcm_employment_periods(person_id);


-- H12: Termination reason lookup
CREATE TABLE IF NOT EXISTS hcm_termination_reasons (
    reason_id                    SERIAL PRIMARY KEY,
    reason_code                  VARCHAR(20) UNIQUE NOT NULL,
    reason_name                  VARCHAR(100) NOT NULL,
    reason_category              VARCHAR(30),
    is_voluntary                 BOOLEAN DEFAULT TRUE,
    created_at                TIMESTAMP DEFAULT NOW()
);


-- H13: Workforce lifecycle actions (hire/transfer/promote/terminate)
CREATE TABLE IF NOT EXISTS hcm_workforce_actions (
    action_id                    SERIAL PRIMARY KEY,
    person_id                    INTEGER REFERENCES hcm_persons(person_id) ON DELETE RESTRICT,
    assignment_id                INTEGER REFERENCES hcm_assignments(assignment_id),
    action_type                  VARCHAR(30) NOT NULL,
    action_reason                VARCHAR(100),
    effective_date               DATE NOT NULL,
    reason_id                    INTEGER REFERENCES hcm_termination_reasons(reason_id),
    old_value                    VARCHAR(200),
    new_value                    VARCHAR(200),
    processed_by                 INTEGER REFERENCES hcm_persons(person_id),
    status                       VARCHAR(20) DEFAULT 'COMPLETED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_workforce_actions_person_id ON hcm_workforce_actions(person_id);
CREATE INDEX IF NOT EXISTS idx_hcm_workforce_actions_assignment_id ON hcm_workforce_actions(assignment_id);


-- H14: Promotion history linked to assignment
CREATE TABLE IF NOT EXISTS hcm_promotions (
    promotion_id                 SERIAL PRIMARY KEY,
    assignment_id                INTEGER REFERENCES hcm_assignments(assignment_id) ON DELETE RESTRICT,
    effective_date               DATE NOT NULL,
    old_grade                    VARCHAR(10),
    new_grade                    VARCHAR(10),
    old_job_title                VARCHAR(100),
    new_job_title                VARCHAR(100),
    old_salary                   NUMERIC(12,2),
    new_salary                   NUMERIC(12,2),
    approved_by                  INTEGER REFERENCES hcm_persons(person_id),
    status                       VARCHAR(20) DEFAULT 'APPROVED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_promotions_assignment_id ON hcm_promotions(assignment_id);


-- H15: Transfer history linked to assignment
CREATE TABLE IF NOT EXISTS hcm_transfers (
    transfer_id                  SERIAL PRIMARY KEY,
    assignment_id                INTEGER REFERENCES hcm_assignments(assignment_id) ON DELETE RESTRICT,
    effective_date               DATE NOT NULL,
    from_dept_id                 INTEGER REFERENCES hcm_departments(dept_id),
    to_dept_id                   INTEGER REFERENCES hcm_departments(dept_id),
    from_location_id             INTEGER REFERENCES hcm_locations(location_id),
    to_location_id               INTEGER REFERENCES hcm_locations(location_id),
    transfer_reason              VARCHAR(100),
    approved_by                  INTEGER REFERENCES hcm_persons(person_id),
    status                       VARCHAR(20) DEFAULT 'APPROVED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_transfers_assignment_id ON hcm_transfers(assignment_id);


-- H16: Salary change history per assignment
CREATE TABLE IF NOT EXISTS hcm_salary_history (
    salary_history_id            SERIAL PRIMARY KEY,
    assignment_id                INTEGER REFERENCES hcm_assignments(assignment_id) ON DELETE RESTRICT,
    old_salary                   NUMERIC(12,2),
    new_salary                   NUMERIC(12,2) NOT NULL,
    change_reason                VARCHAR(50),
    effective_date               DATE NOT NULL,
    currency                     VARCHAR(3) DEFAULT 'GBP',
    approved_by                  INTEGER REFERENCES hcm_persons(person_id),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_salary_history_assignment_id ON hcm_salary_history(assignment_id);


-- H17: Pay components (base, bonus, allowances) per assignment
CREATE TABLE IF NOT EXISTS hcm_compensation_elements (
    element_id                   SERIAL PRIMARY KEY,
    assignment_id                INTEGER REFERENCES hcm_assignments(assignment_id) ON DELETE RESTRICT,
    element_type                 VARCHAR(30) NOT NULL,
    element_name                 VARCHAR(100) NOT NULL,
    amount                       NUMERIC(12,2) NOT NULL,
    frequency                    VARCHAR(20) DEFAULT 'MONTHLY',
    currency                     VARCHAR(3) DEFAULT 'GBP',
    effective_from               DATE,
    effective_to                 DATE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_compensation_elements_assignment_id ON hcm_compensation_elements(assignment_id);


-- H18: Payroll batch run headers
CREATE TABLE IF NOT EXISTS hcm_payroll_runs (
    payroll_run_id               SERIAL PRIMARY KEY,
    run_name                     VARCHAR(100) NOT NULL,
    period_name                  VARCHAR(20) NOT NULL,
    run_date                     DATE NOT NULL,
    status                       VARCHAR(20) DEFAULT 'COMPLETED',
    total_gross                  NUMERIC(15,2),
    total_deductions             NUMERIC(15,2),
    total_net                    NUMERIC(15,2),
    employee_count               INTEGER,
    created_at                TIMESTAMP DEFAULT NOW()
);


-- H19: Individual payroll results per assignment per run
CREATE TABLE IF NOT EXISTS hcm_payroll_results (
    result_id                    SERIAL PRIMARY KEY,
    payroll_run_id               INTEGER REFERENCES hcm_payroll_runs(payroll_run_id) ON DELETE RESTRICT,
    assignment_id                INTEGER REFERENCES hcm_assignments(assignment_id) ON DELETE RESTRICT,
    gross_pay                    NUMERIC(12,2),
    tax_deducted                 NUMERIC(12,2),
    ni_deducted                  NUMERIC(12,2),
    pension_deducted             NUMERIC(12,2),
    other_deductions             NUMERIC(12,2) DEFAULT 0,
    net_pay                      NUMERIC(12,2),
    account_code_id              INTEGER,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_payroll_results_payroll_run_id ON hcm_payroll_results(payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_hcm_payroll_results_assignment_id ON hcm_payroll_results(assignment_id);


-- H20: Assignment cost allocation to finance cost centres (cross-domain)
CREATE TABLE IF NOT EXISTS hcm_cost_allocations (
    allocation_id                SERIAL PRIMARY KEY,
    assignment_id                INTEGER REFERENCES hcm_assignments(assignment_id) ON DELETE RESTRICT,
    cost_centre_id               INTEGER,
    allocation_pct               NUMERIC(5,2) DEFAULT 100.00,
    effective_from               DATE NOT NULL,
    effective_to                 DATE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_cost_allocations_assignment_id ON hcm_cost_allocations(assignment_id);


-- H21: Performance reviews linked to person
CREATE TABLE IF NOT EXISTS hcm_performance_reviews (
    review_id                    SERIAL PRIMARY KEY,
    person_id                    INTEGER REFERENCES hcm_persons(person_id) ON DELETE RESTRICT,
    reviewer_person_id           INTEGER REFERENCES hcm_persons(person_id),
    review_period                VARCHAR(20) NOT NULL,
    review_type                  VARCHAR(20) DEFAULT 'ANNUAL',
    overall_rating               VARCHAR(30),
    rating_score                 NUMERIC(3,1),
    goals_met_pct                NUMERIC(5,2),
    comments                     TEXT,
    status                       VARCHAR(20) DEFAULT 'COMPLETED',
    review_date                  DATE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_performance_reviews_person_id ON hcm_performance_reviews(person_id);


-- H22: Training and certification records
CREATE TABLE IF NOT EXISTS hcm_training_records (
    training_id                  SERIAL PRIMARY KEY,
    person_id                    INTEGER REFERENCES hcm_persons(person_id) ON DELETE RESTRICT,
    course_name                  VARCHAR(150) NOT NULL,
    course_category              VARCHAR(50),
    provider                     VARCHAR(100),
    completion_date              DATE,
    score                        NUMERIC(5,2),
    status                       VARCHAR(20) DEFAULT 'COMPLETED',
    certificate_id               VARCHAR(50),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hcm_training_records_person_id ON hcm_training_records(person_id);


-- ================================================================
--                    FINANCE DOMAIN (23 TABLES)
-- ================================================================

-- F1: General ledger definitions
CREATE TABLE IF NOT EXISTS fin_ledgers (
    ledger_id                    SERIAL PRIMARY KEY,
    ledger_code                  VARCHAR(20) UNIQUE NOT NULL,
    ledger_name                  VARCHAR(100) NOT NULL,
    currency                     VARCHAR(3) DEFAULT 'GBP',
    calendar_type                VARCHAR(20) DEFAULT 'FISCAL',
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);


-- F2: Chart of accounts structure
CREATE TABLE IF NOT EXISTS fin_chart_of_accounts (
    coa_id                       SERIAL PRIMARY KEY,
    coa_code                     VARCHAR(20) UNIQUE NOT NULL,
    coa_name                     VARCHAR(100) NOT NULL,
    ledger_id                    INTEGER REFERENCES fin_ledgers(ledger_id),
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_chart_of_accounts_ledger_id ON fin_chart_of_accounts(ledger_id);


-- F3: COA segment definitions (company, dept, account, etc.)
CREATE TABLE IF NOT EXISTS fin_coa_segments (
    segment_id                   SERIAL PRIMARY KEY,
    coa_id                       INTEGER REFERENCES fin_chart_of_accounts(coa_id) ON DELETE RESTRICT,
    segment_name                 VARCHAR(50) NOT NULL,
    segment_number               INTEGER NOT NULL,
    segment_type                 VARCHAR(30),
    value_set                    VARCHAR(50),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_coa_segments_coa_id ON fin_coa_segments(coa_id);


-- F4: Cost centre master (cross-domain link to HCM)
CREATE TABLE IF NOT EXISTS fin_cost_centres (
    cost_centre_id               SERIAL PRIMARY KEY,
    cost_centre_code             VARCHAR(20) UNIQUE NOT NULL,
    cost_centre_name             VARCHAR(100) NOT NULL,
    dept_id                      INTEGER REFERENCES hcm_departments(dept_id),
    manager_person_id            INTEGER REFERENCES hcm_persons(person_id),
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_cost_centres_dept_id ON fin_cost_centres(dept_id);


-- Deferred FK: hcm_cost_allocations → fin_cost_centres
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_hcm_ca_cc') THEN
    ALTER TABLE hcm_cost_allocations ADD CONSTRAINT fk_hcm_ca_cc
      FOREIGN KEY (cost_centre_id) REFERENCES fin_cost_centres(cost_centre_id) ON DELETE RESTRICT;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_hcm_cost_allocations_cost_centre_id ON hcm_cost_allocations(cost_centre_id);


-- F5: Account code master
CREATE TABLE IF NOT EXISTS fin_account_codes (
    account_code_id              SERIAL PRIMARY KEY,
    account_code                 VARCHAR(20) UNIQUE NOT NULL,
    account_name                 VARCHAR(100) NOT NULL,
    account_type                 VARCHAR(30) NOT NULL,
    parent_account_code          VARCHAR(20),
    coa_id                       INTEGER REFERENCES fin_chart_of_accounts(coa_id),
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_account_codes_coa_id ON fin_account_codes(coa_id);

-- Deferred FK: hcm_payroll_results → fin_account_codes
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_hcm_pr_ac') THEN
    ALTER TABLE hcm_payroll_results ADD CONSTRAINT fk_hcm_pr_ac
      FOREIGN KEY (account_code_id) REFERENCES fin_account_codes(account_code_id) ON DELETE RESTRICT;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_hcm_payroll_results_account_code_id ON hcm_payroll_results(account_code_id);


-- F6: Fiscal reporting periods
CREATE TABLE IF NOT EXISTS fin_reporting_periods (
    period_id                    SERIAL PRIMARY KEY,
    period_name                  VARCHAR(20) UNIQUE NOT NULL,
    fiscal_year                  INTEGER NOT NULL,
    fiscal_quarter               INTEGER NOT NULL,
    period_number                INTEGER NOT NULL,
    start_date                   DATE NOT NULL,
    end_date                     DATE NOT NULL,
    status                       VARCHAR(20) DEFAULT 'OPEN',
    created_at                TIMESTAMP DEFAULT NOW()
);


-- F7: Currency exchange rates
CREATE TABLE IF NOT EXISTS fin_currency_rates (
    rate_id                      SERIAL PRIMARY KEY,
    from_currency                VARCHAR(3) NOT NULL,
    to_currency                  VARCHAR(3) NOT NULL,
    exchange_rate                NUMERIC(12,6) NOT NULL,
    rate_type                    VARCHAR(20) DEFAULT 'SPOT',
    effective_date               DATE NOT NULL,
    created_at                TIMESTAMP DEFAULT NOW()
);


-- F8: GL journal entry headers
CREATE TABLE IF NOT EXISTS fin_gl_journal_headers (
    journal_header_id            SERIAL PRIMARY KEY,
    journal_number               VARCHAR(30) UNIQUE NOT NULL,
    journal_name                 VARCHAR(150),
    ledger_id                    INTEGER REFERENCES fin_ledgers(ledger_id),
    period_id                    INTEGER REFERENCES fin_reporting_periods(period_id),
    journal_date                 DATE NOT NULL,
    journal_source               VARCHAR(30),
    journal_category             VARCHAR(30),
    total_debit                  NUMERIC(15,2),
    total_credit                 NUMERIC(15,2),
    status                       VARCHAR(20) DEFAULT 'POSTED',
    created_by                   INTEGER REFERENCES hcm_persons(person_id),
    approved_by                  INTEGER REFERENCES hcm_persons(person_id),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_gl_journal_headers_ledger_id ON fin_gl_journal_headers(ledger_id);
CREATE INDEX IF NOT EXISTS idx_fin_gl_journal_headers_period_id ON fin_gl_journal_headers(period_id);


-- F9: GL journal lines with account + cost centre
CREATE TABLE IF NOT EXISTS fin_gl_journal_lines (
    journal_line_id              SERIAL PRIMARY KEY,
    journal_header_id            INTEGER REFERENCES fin_gl_journal_headers(journal_header_id) ON DELETE RESTRICT,
    line_number                  INTEGER NOT NULL,
    account_code_id              INTEGER REFERENCES fin_account_codes(account_code_id) ON DELETE RESTRICT,
    cost_centre_id               INTEGER REFERENCES fin_cost_centres(cost_centre_id) ON DELETE RESTRICT,
    debit_amount                 NUMERIC(15,2) DEFAULT 0,
    credit_amount                NUMERIC(15,2) DEFAULT 0,
    description                  VARCHAR(255),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_gl_journal_lines_journal_header_id ON fin_gl_journal_lines(journal_header_id);
CREATE INDEX IF NOT EXISTS idx_fin_gl_journal_lines_account_code_id ON fin_gl_journal_lines(account_code_id);
CREATE INDEX IF NOT EXISTS idx_fin_gl_journal_lines_cost_centre_id ON fin_gl_journal_lines(cost_centre_id);


-- F10: GL summary balances (derived from journal lines, not directly updated)
CREATE TABLE IF NOT EXISTS fin_gl_balances (
    balance_id                   SERIAL PRIMARY KEY,
    cost_centre_id               INTEGER REFERENCES fin_cost_centres(cost_centre_id),
    account_code_id              INTEGER REFERENCES fin_account_codes(account_code_id),
    period_name                  VARCHAR(20) NOT NULL,
    fiscal_year                  INTEGER,
    fiscal_quarter               INTEGER,
    period_debit                 NUMERIC(15,2),
    period_credit                NUMERIC(15,2),
    period_net                   NUMERIC(15,2),
    begin_balance                NUMERIC(15,2),
    end_balance                  NUMERIC(15,2),
    currency                     VARCHAR(3) DEFAULT 'GBP',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_gl_balances_cost_centre_id ON fin_gl_balances(cost_centre_id);
CREATE INDEX IF NOT EXISTS idx_fin_gl_balances_account_code_id ON fin_gl_balances(account_code_id);
CREATE INDEX IF NOT EXISTS idx_fin_gl_balances_period_name ON fin_gl_balances(period_name);


-- F11: Budget version control (original, revised, forecast)
CREATE TABLE IF NOT EXISTS fin_budget_versions (
    budget_version_id            SERIAL PRIMARY KEY,
    version_name                 VARCHAR(50) NOT NULL,
    version_type                 VARCHAR(20) DEFAULT 'ORIGINAL',
    fiscal_year                  INTEGER NOT NULL,
    status                       VARCHAR(20) DEFAULT 'APPROVED',
    created_at                TIMESTAMP DEFAULT NOW()
);


-- F12: Budget headers per ledger
CREATE TABLE IF NOT EXISTS fin_budget_headers (
    budget_header_id             SERIAL PRIMARY KEY,
    budget_name                  VARCHAR(100) NOT NULL,
    ledger_id                    INTEGER REFERENCES fin_ledgers(ledger_id),
    budget_version_id            INTEGER REFERENCES fin_budget_versions(budget_version_id),
    fiscal_year                  INTEGER NOT NULL,
    total_amount                 NUMERIC(15,2),
    status                       VARCHAR(20) DEFAULT 'APPROVED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_budget_headers_ledger_id ON fin_budget_headers(ledger_id);
CREATE INDEX IF NOT EXISTS idx_fin_budget_headers_budget_version_id ON fin_budget_headers(budget_version_id);


-- F13: Budget line amounts at cost centre + account level
CREATE TABLE IF NOT EXISTS fin_budget_lines (
    budget_line_id               SERIAL PRIMARY KEY,
    budget_header_id             INTEGER REFERENCES fin_budget_headers(budget_header_id) ON DELETE RESTRICT,
    cost_centre_id               INTEGER REFERENCES fin_cost_centres(cost_centre_id) ON DELETE RESTRICT,
    account_code_id              INTEGER REFERENCES fin_account_codes(account_code_id) ON DELETE RESTRICT,
    period_name                  VARCHAR(20) NOT NULL,
    amount                       NUMERIC(15,2) NOT NULL,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_budget_lines_budget_header_id ON fin_budget_lines(budget_header_id);
CREATE INDEX IF NOT EXISTS idx_fin_budget_lines_cost_centre_id ON fin_budget_lines(cost_centre_id);
CREATE INDEX IF NOT EXISTS idx_fin_budget_lines_account_code_id ON fin_budget_lines(account_code_id);


-- ================================================================
--               UNIFIED SUPPLIER MASTER (3 TABLES)
-- ================================================================

-- Unified supplier master -- referenced by BOTH Finance AP and Procurement
CREATE TABLE IF NOT EXISTS sup_suppliers (
    supplier_id                  SERIAL PRIMARY KEY,
    supplier_number              VARCHAR(20) UNIQUE NOT NULL,
    supplier_name                VARCHAR(150) NOT NULL,
    tax_registration             VARCHAR(30),
    payment_terms                VARCHAR(30) DEFAULT 'NET30',
    supplier_type                VARCHAR(30),
    risk_rating                  VARCHAR(10),
    qualification_status         VARCHAR(20) DEFAULT 'QUALIFIED',
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    country                      VARCHAR(50) DEFAULT 'United Kingdom',
    created_at                TIMESTAMP DEFAULT NOW(),
    updated_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sup_suppliers_status ON sup_suppliers(status);


-- Supplier sites / addresses
CREATE TABLE IF NOT EXISTS sup_supplier_sites (
    site_id                      SERIAL PRIMARY KEY,
    supplier_id                  INTEGER REFERENCES sup_suppliers(supplier_id) ON DELETE RESTRICT,
    site_code                    VARCHAR(20) NOT NULL,
    site_name                    VARCHAR(100),
    address_line1                VARCHAR(200),
    city                         VARCHAR(50),
    postal_code                  VARCHAR(15),
    country                      VARCHAR(50) DEFAULT 'United Kingdom',
    is_primary                   BOOLEAN DEFAULT FALSE,
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sup_supplier_sites_supplier_id ON sup_supplier_sites(supplier_id);


-- Supplier contact persons
CREATE TABLE IF NOT EXISTS sup_supplier_contacts (
    contact_id                   SERIAL PRIMARY KEY,
    supplier_id                  INTEGER REFERENCES sup_suppliers(supplier_id) ON DELETE RESTRICT,
    contact_name                 VARCHAR(100) NOT NULL,
    job_title                    VARCHAR(100),
    email                        VARCHAR(150),
    phone                        VARCHAR(30),
    is_primary                   BOOLEAN DEFAULT FALSE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sup_supplier_contacts_supplier_id ON sup_supplier_contacts(supplier_id);


-- ---- Accounts Payable ----

-- F14: AP invoices referencing unified supplier master
CREATE TABLE IF NOT EXISTS fin_ap_invoices (
    invoice_id                   SERIAL PRIMARY KEY,
    invoice_number               VARCHAR(50) UNIQUE NOT NULL,
    supplier_id                  INTEGER REFERENCES sup_suppliers(supplier_id) ON DELETE RESTRICT,
    ledger_id                    INTEGER REFERENCES fin_ledgers(ledger_id),
    invoice_date                 DATE NOT NULL,
    due_date                     DATE,
    invoice_amount               NUMERIC(15,2) NOT NULL,
    paid_amount                  NUMERIC(15,2) DEFAULT 0,
    outstanding_amount           NUMERIC(15,2),
    currency                     VARCHAR(3) DEFAULT 'GBP',
    status                       VARCHAR(20) DEFAULT 'PENDING',
    created_by                   INTEGER REFERENCES hcm_persons(person_id),
    approved_by                  INTEGER REFERENCES hcm_persons(person_id),
    created_at                TIMESTAMP DEFAULT NOW(),
    updated_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoices_supplier_id ON fin_ap_invoices(supplier_id);
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoices_status ON fin_ap_invoices(status);
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoices_due_date ON fin_ap_invoices(due_date);


-- F15: AP invoice lines (po_line_id FK deferred for 3-way match)
CREATE TABLE IF NOT EXISTS fin_ap_invoice_lines (
    invoice_line_id              SERIAL PRIMARY KEY,
    invoice_id                   INTEGER REFERENCES fin_ap_invoices(invoice_id) ON DELETE RESTRICT,
    line_number                  INTEGER NOT NULL,
    description                  VARCHAR(255),
    quantity                     NUMERIC(10,2) DEFAULT 1,
    unit_price                   NUMERIC(12,2),
    line_amount                  NUMERIC(12,2),
    po_line_id                   INTEGER,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoice_lines_invoice_id ON fin_ap_invoice_lines(invoice_id);


-- F16: AP invoice accounting distributions
CREATE TABLE IF NOT EXISTS fin_ap_invoice_distributions (
    distribution_id              SERIAL PRIMARY KEY,
    invoice_line_id              INTEGER REFERENCES fin_ap_invoice_lines(invoice_line_id) ON DELETE RESTRICT,
    cost_centre_id               INTEGER REFERENCES fin_cost_centres(cost_centre_id) ON DELETE RESTRICT,
    account_code_id              INTEGER REFERENCES fin_account_codes(account_code_id) ON DELETE RESTRICT,
    distribution_pct             NUMERIC(5,2) DEFAULT 100.00,
    amount                       NUMERIC(12,2),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoice_distributions_invoice_line_id ON fin_ap_invoice_distributions(invoice_line_id);
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoice_distributions_cost_centre_id ON fin_ap_invoice_distributions(cost_centre_id);
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoice_distributions_account_code_id ON fin_ap_invoice_distributions(account_code_id);


-- F17: AP payment schedules per invoice
CREATE TABLE IF NOT EXISTS fin_ap_payment_schedules (
    schedule_id                  SERIAL PRIMARY KEY,
    invoice_id                   INTEGER REFERENCES fin_ap_invoices(invoice_id) ON DELETE RESTRICT,
    installment_num              INTEGER DEFAULT 1,
    due_date                     DATE NOT NULL,
    amount_due                   NUMERIC(12,2) NOT NULL,
    amount_paid                  NUMERIC(12,2) DEFAULT 0,
    status                       VARCHAR(20) DEFAULT 'OPEN',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_ap_payment_schedules_invoice_id ON fin_ap_payment_schedules(invoice_id);


-- F18: AP payment records
CREATE TABLE IF NOT EXISTS fin_ap_payments (
    payment_id                   SERIAL PRIMARY KEY,
    payment_number               VARCHAR(30) UNIQUE NOT NULL,
    supplier_id                  INTEGER REFERENCES sup_suppliers(supplier_id) ON DELETE RESTRICT,
    payment_date                 DATE NOT NULL,
    payment_amount               NUMERIC(15,2) NOT NULL,
    payment_method               VARCHAR(20) DEFAULT 'BACS',
    reference                    VARCHAR(50),
    status                       VARCHAR(20) DEFAULT 'COMPLETED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_ap_payments_supplier_id ON fin_ap_payments(supplier_id);


-- ---- Accounts Receivable ----

-- F19: AR customer master
CREATE TABLE IF NOT EXISTS fin_ar_customers (
    customer_id                  SERIAL PRIMARY KEY,
    customer_number              VARCHAR(20) UNIQUE NOT NULL,
    customer_name                VARCHAR(150) NOT NULL,
    customer_type                VARCHAR(30),
    payment_terms                VARCHAR(30) DEFAULT 'NET30',
    credit_limit                 NUMERIC(15,2),
    contact_name                 VARCHAR(100),
    contact_email                VARCHAR(150),
    country                      VARCHAR(50) DEFAULT 'United Kingdom',
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);


-- F20: AR invoices
CREATE TABLE IF NOT EXISTS fin_ar_invoices (
    ar_invoice_id                SERIAL PRIMARY KEY,
    invoice_number               VARCHAR(50) UNIQUE NOT NULL,
    customer_id                  INTEGER REFERENCES fin_ar_customers(customer_id) ON DELETE RESTRICT,
    invoice_date                 DATE NOT NULL,
    due_date                     DATE NOT NULL,
    invoice_amount               NUMERIC(15,2) NOT NULL,
    paid_amount                  NUMERIC(15,2) DEFAULT 0,
    outstanding                  NUMERIC(15,2),
    currency                     VARCHAR(3) DEFAULT 'GBP',
    status                       VARCHAR(20) DEFAULT 'OPEN',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_ar_invoices_customer_id ON fin_ar_invoices(customer_id);


-- F21: AR receipts (customer payments)
CREATE TABLE IF NOT EXISTS fin_ar_receipts (
    receipt_id                   SERIAL PRIMARY KEY,
    receipt_number               VARCHAR(30) UNIQUE NOT NULL,
    ar_invoice_id                INTEGER REFERENCES fin_ar_invoices(ar_invoice_id) ON DELETE RESTRICT,
    receipt_date                 DATE NOT NULL,
    receipt_amount               NUMERIC(15,2) NOT NULL,
    payment_method               VARCHAR(20) DEFAULT 'BACS',
    status                       VARCHAR(20) DEFAULT 'APPLIED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fin_ar_receipts_ar_invoice_id ON fin_ar_receipts(ar_invoice_id);


-- ================================================================
--                 PROCUREMENT DOMAIN (17 TABLES)
-- ================================================================

-- P1: Item category hierarchy (self-referencing)
CREATE TABLE IF NOT EXISTS proc_item_categories (
    category_id                  SERIAL PRIMARY KEY,
    category_code                VARCHAR(20) UNIQUE NOT NULL,
    category_name                VARCHAR(100) NOT NULL,
    parent_category_id           INTEGER REFERENCES proc_item_categories(category_id),
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_item_categories_parent_category_id ON proc_item_categories(parent_category_id);


-- P2: Item / service catalog
CREATE TABLE IF NOT EXISTS proc_items (
    item_id                      SERIAL PRIMARY KEY,
    item_code                    VARCHAR(20) UNIQUE NOT NULL,
    item_name                    VARCHAR(150) NOT NULL,
    description                  VARCHAR(255),
    category_id                  INTEGER REFERENCES proc_item_categories(category_id),
    unit_of_measure              VARCHAR(20) DEFAULT 'EACH',
    unit_price                   NUMERIC(12,2),
    item_type                    VARCHAR(20) DEFAULT 'SERVICE',
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_items_category_id ON proc_items(category_id);


-- P3: Purchase requisition headers (cross-domain → HCM)
CREATE TABLE IF NOT EXISTS proc_requisition_headers (
    requisition_id               SERIAL PRIMARY KEY,
    requisition_number           VARCHAR(30) UNIQUE NOT NULL,
    requester_id                 INTEGER REFERENCES hcm_persons(person_id),
    dept_id                      INTEGER REFERENCES hcm_departments(dept_id),
    description                  VARCHAR(255),
    justification                TEXT,
    total_amount                 NUMERIC(15,2),
    status                       VARCHAR(20) DEFAULT 'APPROVED',
    submitted_date               DATE,
    approved_date                DATE,
    approved_by                  INTEGER REFERENCES hcm_persons(person_id),
    created_at                TIMESTAMP DEFAULT NOW(),
    updated_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_requisition_headers_requester_id ON proc_requisition_headers(requester_id);
CREATE INDEX IF NOT EXISTS idx_proc_requisition_headers_dept_id ON proc_requisition_headers(dept_id);


-- P4: Requisition line items
CREATE TABLE IF NOT EXISTS proc_requisition_lines (
    req_line_id                  SERIAL PRIMARY KEY,
    requisition_id               INTEGER REFERENCES proc_requisition_headers(requisition_id) ON DELETE RESTRICT,
    line_number                  INTEGER NOT NULL,
    item_id                      INTEGER REFERENCES proc_items(item_id),
    description                  VARCHAR(255),
    quantity                     NUMERIC(10,2) DEFAULT 1,
    unit_price                   NUMERIC(12,2),
    line_amount                  NUMERIC(12,2),
    need_by_date                 DATE,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_requisition_lines_requisition_id ON proc_requisition_lines(requisition_id);
CREATE INDEX IF NOT EXISTS idx_proc_requisition_lines_item_id ON proc_requisition_lines(item_id);


-- P5: Requisition accounting distributions
CREATE TABLE IF NOT EXISTS proc_requisition_distributions (
    req_dist_id                  SERIAL PRIMARY KEY,
    req_line_id                  INTEGER REFERENCES proc_requisition_lines(req_line_id) ON DELETE RESTRICT,
    cost_centre_id               INTEGER REFERENCES fin_cost_centres(cost_centre_id) ON DELETE RESTRICT,
    account_code_id              INTEGER REFERENCES fin_account_codes(account_code_id) ON DELETE RESTRICT,
    distribution_pct             NUMERIC(5,2) DEFAULT 100.00,
    amount                       NUMERIC(12,2),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_requisition_distributions_req_line_id ON proc_requisition_distributions(req_line_id);
CREATE INDEX IF NOT EXISTS idx_proc_requisition_distributions_cost_centre_id ON proc_requisition_distributions(cost_centre_id);
CREATE INDEX IF NOT EXISTS idx_proc_requisition_distributions_account_code_id ON proc_requisition_distributions(account_code_id);


-- P6: Quotation headers linked to unified supplier
CREATE TABLE IF NOT EXISTS proc_quotation_headers (
    quotation_header_id          SERIAL PRIMARY KEY,
    quotation_number             VARCHAR(30) UNIQUE NOT NULL,
    engagement_id                VARCHAR(30) NOT NULL,
    engagement_name              VARCHAR(200),
    supplier_id                  INTEGER REFERENCES sup_suppliers(supplier_id) ON DELETE RESTRICT,
    original_amount              NUMERIC(15,2),
    revised_amount               NUMERIC(15,2),
    status                       VARCHAR(20),
    submission_date              DATE,
    category                     VARCHAR(50),
    created_at                TIMESTAMP DEFAULT NOW(),
    updated_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_quotation_headers_supplier_id ON proc_quotation_headers(supplier_id);
CREATE INDEX IF NOT EXISTS idx_proc_quotation_headers_engagement_id ON proc_quotation_headers(engagement_id);


-- P7: Quotation line items
CREATE TABLE IF NOT EXISTS proc_quotation_lines (
    quot_line_id                 SERIAL PRIMARY KEY,
    quotation_header_id          INTEGER REFERENCES proc_quotation_headers(quotation_header_id) ON DELETE RESTRICT,
    line_number                  INTEGER NOT NULL,
    item_id                      INTEGER REFERENCES proc_items(item_id),
    description                  VARCHAR(255),
    quantity                     NUMERIC(10,2) DEFAULT 1,
    unit_price                   NUMERIC(12,2),
    line_amount                  NUMERIC(12,2),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_quotation_lines_quotation_header_id ON proc_quotation_lines(quotation_header_id);


-- P8: Quotation version history for audit trail
CREATE TABLE IF NOT EXISTS proc_quote_versions (
    version_id                   SERIAL PRIMARY KEY,
    quotation_header_id          INTEGER REFERENCES proc_quotation_headers(quotation_header_id) ON DELETE RESTRICT,
    version_number               INTEGER NOT NULL,
    version_amount               NUMERIC(15,2),
    submitted_date               DATE,
    status                       VARCHAR(20),
    change_notes                 TEXT,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_quote_versions_quotation_header_id ON proc_quote_versions(quotation_header_id);


-- P9: PO headers (cross-domain → supplier + HCM buyer)
CREATE TABLE IF NOT EXISTS proc_po_headers (
    po_header_id                 SERIAL PRIMARY KEY,
    po_number                    VARCHAR(50) UNIQUE NOT NULL,
    supplier_id                  INTEGER REFERENCES sup_suppliers(supplier_id) ON DELETE RESTRICT,
    requisition_id               INTEGER REFERENCES proc_requisition_headers(requisition_id),
    buyer_id                     INTEGER REFERENCES hcm_persons(person_id),
    total_amount                 NUMERIC(15,2),
    approved_amount              NUMERIC(15,2),
    status                       VARCHAR(20) DEFAULT 'PENDING',
    created_date                 DATE,
    approved_date                DATE,
    approved_by                  INTEGER REFERENCES hcm_persons(person_id),
    category                     VARCHAR(50),
    created_at                TIMESTAMP DEFAULT NOW(),
    updated_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_po_headers_supplier_id ON proc_po_headers(supplier_id);
CREATE INDEX IF NOT EXISTS idx_proc_po_headers_buyer_id ON proc_po_headers(buyer_id);
CREATE INDEX IF NOT EXISTS idx_proc_po_headers_requisition_id ON proc_po_headers(requisition_id);
CREATE INDEX IF NOT EXISTS idx_proc_po_headers_status ON proc_po_headers(status);


-- P10: PO line items
CREATE TABLE IF NOT EXISTS proc_po_lines (
    po_line_id                   SERIAL PRIMARY KEY,
    po_header_id                 INTEGER REFERENCES proc_po_headers(po_header_id) ON DELETE RESTRICT,
    line_number                  INTEGER NOT NULL,
    item_id                      INTEGER REFERENCES proc_items(item_id),
    description                  VARCHAR(255),
    quantity                     NUMERIC(10,2) DEFAULT 1,
    unit_price                   NUMERIC(12,2),
    line_amount                  NUMERIC(12,2),
    status                       VARCHAR(20) DEFAULT 'OPEN',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_po_lines_po_header_id ON proc_po_lines(po_header_id);
CREATE INDEX IF NOT EXISTS idx_proc_po_lines_item_id ON proc_po_lines(item_id);

-- Deferred FK: fin_ap_invoice_lines.po_line_id → proc_po_lines (3-way match)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_ap_il_pol') THEN
    ALTER TABLE fin_ap_invoice_lines ADD CONSTRAINT fk_ap_il_pol
      FOREIGN KEY (po_line_id) REFERENCES proc_po_lines(po_line_id) ON DELETE RESTRICT;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_fin_ap_invoice_lines_po_line_id ON fin_ap_invoice_lines(po_line_id);


-- P11: PO accounting distributions (cross-domain → Finance)
CREATE TABLE IF NOT EXISTS proc_po_distributions (
    po_dist_id                   SERIAL PRIMARY KEY,
    po_line_id                   INTEGER REFERENCES proc_po_lines(po_line_id) ON DELETE RESTRICT,
    cost_centre_id               INTEGER REFERENCES fin_cost_centres(cost_centre_id) ON DELETE RESTRICT,
    account_code_id              INTEGER REFERENCES fin_account_codes(account_code_id) ON DELETE RESTRICT,
    distribution_pct             NUMERIC(5,2) DEFAULT 100.00,
    amount                       NUMERIC(12,2),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_po_distributions_po_line_id ON proc_po_distributions(po_line_id);
CREATE INDEX IF NOT EXISTS idx_proc_po_distributions_cost_centre_id ON proc_po_distributions(cost_centre_id);
CREATE INDEX IF NOT EXISTS idx_proc_po_distributions_account_code_id ON proc_po_distributions(account_code_id);


-- P12: PO approval workflow
CREATE TABLE IF NOT EXISTS proc_po_approvals (
    approval_id                  SERIAL PRIMARY KEY,
    po_header_id                 INTEGER REFERENCES proc_po_headers(po_header_id) ON DELETE RESTRICT,
    approver_id                  INTEGER REFERENCES hcm_persons(person_id),
    approval_level               INTEGER DEFAULT 1,
    action                       VARCHAR(20) NOT NULL,
    comments                     TEXT,
    action_date                  DATE NOT NULL,
    status                       VARCHAR(20) DEFAULT 'APPROVED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_po_approvals_po_header_id ON proc_po_approvals(po_header_id);


-- P13: Goods receipt headers
CREATE TABLE IF NOT EXISTS proc_receipt_headers (
    receipt_header_id            SERIAL PRIMARY KEY,
    receipt_number               VARCHAR(30) UNIQUE NOT NULL,
    po_header_id                 INTEGER REFERENCES proc_po_headers(po_header_id) ON DELETE RESTRICT,
    received_by                  INTEGER REFERENCES hcm_persons(person_id),
    receipt_date                 DATE NOT NULL,
    status                       VARCHAR(20) DEFAULT 'RECEIVED',
    comments                     TEXT,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_receipt_headers_po_header_id ON proc_receipt_headers(po_header_id);


-- P14: Goods receipt lines matched to PO lines
CREATE TABLE IF NOT EXISTS proc_receipt_lines (
    receipt_line_id              SERIAL PRIMARY KEY,
    receipt_header_id            INTEGER REFERENCES proc_receipt_headers(receipt_header_id) ON DELETE RESTRICT,
    po_line_id                   INTEGER REFERENCES proc_po_lines(po_line_id) ON DELETE RESTRICT,
    quantity_received            NUMERIC(10,2),
    quantity_accepted            NUMERIC(10,2),
    quantity_rejected            NUMERIC(10,2) DEFAULT 0,
    inspection_status            VARCHAR(20) DEFAULT 'ACCEPTED',
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_receipt_lines_receipt_header_id ON proc_receipt_lines(receipt_header_id);
CREATE INDEX IF NOT EXISTS idx_proc_receipt_lines_po_line_id ON proc_receipt_lines(po_line_id);


-- P15: Supplier / blanket purchase contracts
CREATE TABLE IF NOT EXISTS proc_contract_headers (
    contract_header_id           SERIAL PRIMARY KEY,
    contract_number              VARCHAR(30) UNIQUE NOT NULL,
    contract_name                VARCHAR(200),
    supplier_id                  INTEGER REFERENCES sup_suppliers(supplier_id) ON DELETE RESTRICT,
    contract_type                VARCHAR(30) DEFAULT 'BLANKET',
    start_date                   DATE,
    end_date                     DATE,
    total_value                  NUMERIC(15,2),
    released_amount              NUMERIC(15,2) DEFAULT 0,
    status                       VARCHAR(20) DEFAULT 'ACTIVE',
    owner_id                     INTEGER REFERENCES hcm_persons(person_id),
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_contract_headers_supplier_id ON proc_contract_headers(supplier_id);


-- P16: Contract line items
CREATE TABLE IF NOT EXISTS proc_contract_lines (
    contract_line_id             SERIAL PRIMARY KEY,
    contract_header_id           INTEGER REFERENCES proc_contract_headers(contract_header_id) ON DELETE RESTRICT,
    line_number                  INTEGER NOT NULL,
    item_id                      INTEGER REFERENCES proc_items(item_id),
    description                  VARCHAR(255),
    quantity                     NUMERIC(10,2),
    unit_price                   NUMERIC(12,2),
    line_amount                  NUMERIC(12,2),
    released_amount              NUMERIC(12,2) DEFAULT 0,
    created_at                TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proc_contract_lines_contract_header_id ON proc_contract_lines(contract_header_id);


-- ================================================================
--   LEGACY COMPATIBILITY: Views matching old 5-table schema
--   so existing tools/queries still work
-- ================================================================

-- View: hcm_employees (maps to hcm_persons + hcm_assignments)
CREATE OR REPLACE VIEW hcm_employees AS
SELECT
    p.person_id                AS employee_id,
    p.person_number            AS employee_number,
    pn.first_name || ' ' || pn.last_name AS full_name,
    pe.email_address           AS email,
    d.dept_name                AS department,
    a.job_title,
    g.grade_code               AS grade_level,
    a.salary,
    ep.start_date              AS hire_date,
    ep.end_date                AS termination_date,
    a.employment_status        AS employment_status,
    l.location_name            AS location,
    a.manager_person_id        AS manager_id,
    a.dept_id,
    a.position_id,
    a.grade_id,
    a.location_id,
    p.nationality,
    p.date_of_birth,
    p.gender,
    p.created_at
FROM hcm_persons p
LEFT JOIN hcm_person_names pn ON pn.person_id = p.person_id
    AND pn.effective_to IS NULL AND pn.name_type = 'GLOBAL'
LEFT JOIN hcm_person_emails pe ON pe.person_id = p.person_id AND pe.is_primary = TRUE
LEFT JOIN hcm_assignments a ON a.person_id = p.person_id
    AND a.assignment_type = 'PRIMARY' AND a.assignment_status = 'ACTIVE'
LEFT JOIN hcm_employment_periods ep ON ep.person_id = p.person_id
    AND ep.status = 'ACTIVE'
LEFT JOIN hcm_departments d ON d.dept_id = a.dept_id
LEFT JOIN hcm_grades g ON g.grade_id = a.grade_id
LEFT JOIN hcm_locations l ON l.location_id = a.location_id;

-- View: procurement_quotations (maps to proc_quotation_headers + proc_quote_versions)
CREATE OR REPLACE VIEW procurement_quotations AS
SELECT
    qh.quotation_header_id     AS quotation_id,
    qh.engagement_id,
    qh.engagement_name,
    s.supplier_name,
    qh.original_amount,
    qh.revised_amount,
    qv.version_number          AS quotation_version,
    COALESCE(qv.status, qh.status) AS status,
    COALESCE(qv.submitted_date, qh.submission_date) AS submission_date,
    qh.category,
    qh.supplier_id,
    qh.created_at
FROM proc_quotation_headers qh
LEFT JOIN sup_suppliers s ON s.supplier_id = qh.supplier_id
LEFT JOIN proc_quote_versions qv ON qv.quotation_header_id = qh.quotation_header_id;

-- View: procurement_purchase_orders (maps to proc_po_headers)
CREATE OR REPLACE VIEW procurement_purchase_orders AS
SELECT
    ph.po_header_id            AS po_id,
    ph.po_number,
    s.supplier_name,
    ph.total_amount,
    ph.approved_amount,
    ph.status,
    ph.created_date,
    ph.approved_date,
    cc.cost_centre_code        AS cost_centre,
    ph.category,
    ph.supplier_id,
    ph.buyer_id,
    ph.created_at
FROM proc_po_headers ph
LEFT JOIN sup_suppliers s ON s.supplier_id = ph.supplier_id
LEFT JOIN proc_po_distributions pd ON pd.po_line_id = (
    SELECT pl.po_line_id FROM proc_po_lines pl WHERE pl.po_header_id = ph.po_header_id LIMIT 1
)
LEFT JOIN fin_cost_centres cc ON cc.cost_centre_id = pd.cost_centre_id;

